project:
  type: website

website:
  title: ""
  navbar:
    left:
      - text: "Inicio"
        href: portada.qmd
      - text: "Introducción"
        href: introduccion.qmd
      - text: "Materiales y Métodos"
        href: materiales.qmd
      - text: "Resultados"
        href: resultados.qmd
      - text: "Discusión"
        href: discusion.qmd
      - text: "Conclusión"
        href: conclusion.qmd
      - text: "Referencias"
        href: referencias.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    hide-title: true